[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "knewkarma"
version = "6.2.0"
description = "A Reddit data analysis toolkit"
authors = ["Richard Mwewa <rly0nheart@duck.com>"]
readme = "README.rst"
license = "MIT License"
homepage = "https://knewkarma.readthedocs.io"
documentation = "https://knewkarma.readthedocs.io"
repository = "https://github.com/rly0nheart/knewkarma"
keywords = ["reddit", "reddit-api", "reddit-data-analysis"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python :: 3",
    "Intended Audience :: Information Technology",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English"
]

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/rly0nheart/knewkarma/issues"

[tool.poetry.dependencies]
python = "^3.10"
aiohttp = "^3.10.5"
pandas = "^2.1.4"
rich-click = "^1.8.3"
matplotlib = { version = "^3.9.2", optional = true }
tokenizers = { version = "^0.19.0", optional = true }
transformers = { version = "^4.44.0", optional = true }


[tool.poetry.extras]
visualisation = ["matplotlib"]
analysis = ["tokenizers", "transformers"]


[tool.poetry.group.dev.dependencies]
black = "^24.4.2"
poetry = "^1.8.3"
pytest = "^8.2.0"
pytest-asyncio = "^0.24.0"
tenacity = "^8.3.0"

[tool.poetry.scripts]
knewkarma = "knewkarma.cli:start"
