name: knewkarma
icon: snap/gui/icon.png
title: Knew Karma
summary: A Reddit Data Analysis Toolkit
description: |
  **Knew Karma** (/nuː ‘kɑːrmə/) is a **Reddit** Data Analysis Toolkit designed to provide an extensive range of
  functionalities for exploring and analysing Reddit data. It includes a **Command-Line Interface (CLI)** snap package, 
  an **Application Programming Interface (API)** to enable an easy integration in other Python Projects and a **Graphical User Interface (GUI)** for Windows machines, 
  making it adaptable for various user preferences. Refer to the wiki (https://knewkarma-wiki.readthedocs.io) for the usage guide.
version: 4.2.0rc1
license: MIT
base: core22
confinement: strict

source-code: https://github.com/bellingcat/knewkarma
issues:
  - https://github.com/bellingcat/knewkarma/issues
donation:
  - https://buymeacoffee.com/rly0nheart/
contact:
  - mailto:rly0nheart@gagpasta.com

parts:
  knewkarma:
    plugin: python
    source: .

type: app
apps:
  knewkarma:
    command: bin/knewkarma
    plugs: [ network, network-bind, home ]
