name: knewkarma
icon: snap/gui/icon.png
title: Knew Karma
summary: A Reddit data analysis toolkit
description: |
  **Knew Karma** (/nuː ‘kɑːrmə/) is a Reddit data analysis toolkit designed to provide an extensive range of
  functionalities for exploring and analysing Reddit data. It includes a **Command-Line Interface (CLI)**, and an
  **Application Programming Interface (API)** to enable an easy integration in other Python Projects. Refer to the documentation (https://knewkarma.readthedocs.io) for the **usage** and **integration** guide.
version: 6.1.0
license: MIT
base: core22
grade: stable
confinement: strict

source-code: https://github.com/bellingcat/knewkarma
issues:
  - https://github.com/bellingcat/knewkarma/issues
donation:
  - https://buymeacoffee.com/rly0nheart/
contact:
  - mailto:rly0nheart@duck.com

parts:
  knewkarma:
    plugin: python
    source: .

type: app
apps:
  knewkarma:
    command: bin/knewkarma
    desktop: snap/gui/knewkarma.desktop
    plugs: [ network, network-bind, home ]
