name: Build and Release Snap Package

on:
  push:
    tags:
      - '*.*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Snapcraft & Build Snap
        uses: snapcore/action-build@v1
        with:
          snapcraft-channel: 'latest/stable'
          snapcraft-args: '--use-multipass'

      - name: Publish Snap
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPSTORE_CREDENTIALS }}
        run: snapcraft push --release stable *.snap

      - name: Notify Success
        if: success()
        run: echo "Snap package successfully built and released!"

      - name: Notify Failure
        if: failure()
        run: echo "Snap package build/release failed."
